### ISSUE TITLE
Don't suggest deprecated functions?

### ISSUE THREAD

**Issue by rmiller335** [shawncplus/phpcomplete.vim#118]
Just installed today and working well.  Part of the reason I installed is that I jump around between languages quite a lot and I can't remember what functions are called.  I autocompleted my way to $x = split("\n", $y), which of course failed because split is deprecated.  Is there any way to restrict the suggestions to current functions?

Thanks,
Bob Miller

**Comment by complex857** [comment]
Hmm. The definition files have not been updated in good few while which should be done. I've the generator files bundled with the plugin (they need work since the format of the documentation pages have changed).

On the `DEPRECATED` note: I believe just because it's DEPRECATED it shouldn't not be offered, things that have been `REMOVED` aren't. 
Problem is that for the example `split()` is that it's still in the docs (it does state it have been removed for PHP 7.0.0), and the metadata generator doesn't look out for this. This need to be added to the generator (also people running now unsupported versions 5.x.x will be out of luck too).
