### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by LukeMauldin** [shawncplus/phpcomplete.vim#55]
Installed plug using Neobundle and restarted vim.  Have the code below and it is not autocompleting.  I have the vim neocomplete plugin installed too.

```
class Employee {
      public $a;
 
      public function add($one) {
          return $this->a + $one;
      }
  }
  $e = new Employee();
  $e->a (should autocomplete here)

**Comment by complex857** [comment]
Thanks for the report! I've tried to look into this and i think it's a because the neocomplete plugin. 

I don't have experience with the neocomplete plugin, but it seems to me that you need to set up
keys in [`g:neocomplete#force_omni_input_patterns`](https://github.com/Shougo/neocomplete.vim/blob/2dd745b42c5b2f562f78129f9fabda31bfeecdc1/doc/neocomplete.txt#L444) for the filetypes you want to have omni completion.
So i think adding something like this in to your vimrc is needed (examle from the [bottom of readme](https://github.com/Shougo/neocomplete.vim/blob/2dd745b42c5b2f562f78129f9fabda31bfeecdc1/README.md#configuration-examples)):
```
let g:neocomplete#sources#omni#input_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
```
However it looks like to me this pattern doesn't encompass every context where phpcomplete plugin could provide suggestions, like simple function names or things to import after an `use` keyword or class names after an `extend` and such. I'm not sure if neocomplete remaps it or, but try hitting the original <kbd>ctrl</kbd>+<kbd>x</kbd> <kbd>o</kbd> mapping and see if it triggers the omni completion or not.

I couldn't try this out myself at this moment because I don't have a lua enabled vim at hand at this moment (neocomplete needs that), but hope this helps.

**Comment by LukeMauldin** [comment]
When using phpcomplete_extended, they instructed me to add this line of code: 
```autocmd FileType php setlocal omnifunc=phpcomplete_extended#CompletePHP```
It works for the phpcomplete_extended plugin, but unfortunately that plugin only supports composer projects which is why I am trying this one.  Does this plugin have an omnifunc?

I tried setting the input_patterns as you described above, but that didn't work.  I also tried manually invoking it via Ctrl-X o but it said omni completion could not find any matches.

**Comment by complex857** [comment]
> Does this plugin have an omnifunc?

Oh sure, it's `phpcomplete#CompletePHP` so you would write:
```
autocmd FileType php setlocal omnifunc=phpcomplete#CompletePHP
```
But this setting should be set up already by vim's default runtime scripts somewhere in [`ftplugin/php.vim`](https://code.google.com/p/vim/source/browse/runtime/ftplugin/php.vim?spec=svn84171683fd6681984b88b7b70d0d3e6a317ac169&r=d1e4abe8342c4adb1890bf1833a6f41f7a310b01#61).

> I also tried manually invoking it via Ctrl-X o but it said omni completion could not find any matches.

This is more interesting, I've had a chance to try out the neocomplete plugin and it doesn't seemed to overwrite the original <kbd>ctrl</kbd>+<kbd>x</kbd> <kbd>o</kbd> mapping so hitting those should always work as expected. I assume you have the phpcomplete_extended omnifunc set up (as you wrote before) and ended up invoking that function.
I'm afraid both completion plugin would want to set up the `omnifuc` setting so both can't be active at the same time, but changing the omnifunc at runtime should be enought to choose between them.

**Comment by LukeMauldin** [comment]
Setting the autocmd above works if I manually invoke 'ctrl+x o'  How would I get the autocomplete to invoke automatically when I type something like $classInstance->....  ?

**Comment by complex857** [comment]
> How would I get the autocomplete to invoke automatically when I type something like $classInstance->.... ?

Now this is where the neocomplete plugin and it's input_patterns option comes to play. If i understand this right you would want to have a pattern like:
```
let g:neocomplete#sources#omni#input_patterns.php = '[^. \t]->\|\h\w*::'
```
set up in your vimrc so that neocomplete will try to run omnicompletion whenever you are after a `->` or a `::` (but as i mentioned there are many other places where omni completion could give you meaningful results).
I've played around a little with the plugin and input patterns and it looks like this in action (this is with neocomplete enabled, and the above input_patterns):
![complete](https://cloud.githubusercontent.com/assets/131617/5985239/0622ecd0-a8e0-11e4-943e-1e152a202da0.gif)
For the completion after the new, I've hit <kbd>ctrl</kbd>+<kbd>x</kbd> <kbd>o</kbd> myself, but on the second line the popup is opened by the neocomplete plugin automatically after the `->`s.

I'm not using any auto-popup type plugins myself, so i don't have a battle-tested pattern for this, but from here, you can go ahead and `input_patterns` to recognize contexts like afther a `class`, `extends`
or a `new` keyword and other places where the plugin could work. For inspiration check out [this section](https://github.com/shawncplus/phpcomplete.vim/blob/1e128c586e1a5757247dac001fe04d2b3d9a9e36/autoload/phpcomplete.vim#L232-L292) of the plugin.

> Also, how will does this plugin work in a project? If a have a class defined in another PHP file, will the plugin read my Git project and do autocompletion?

For anything not built-in to php, or in the current buffer there is <strike>mastercard</strike> [**ctags**](http://ctags.sourceforge.net/). 
Ctags is a static code analyzer that will make a so called "tags" file listing all the interesting symbols from your files. Vim can use these tags files for a bunch of interesting thing so it's useful to have them around. The current stable release of ctags have a pretty bad PHP support but there's a patchset for php that makes it super good, you can read about this [in the project wiki](https://github.com/shawncplus/phpcomplete.vim/wiki/Patched-ctags), i recommend you to use a patched ctags.
The plugin will read your tags to find the classes in your code and use the files's source itself to generate completion results.

I hope this helps.

**Comment by LukeMauldin** [comment]
Thank you vey much for all of your help, by following your instructions and using the ctags plugin, I finally have real PHP autocomplete in Vim!  I tried updating the input_patterns to handle 'new':
```
let g:neocomplete#sources#omni#input_patterns.php = '[^. \t]->\|\h\w*::|new\h'
```
However, it will not autocomplete after new unless I manually invoke omnicompletion with the shortcut.  I am experincing similiar behavior with autocomplete not working after '::' unless I manually invoke it.  Any thoughts?

On a related note, have you used this plugin on large PHP projects?  One of my large projects have a 13 MB tags file and when I try to run omnicomplete sometimes neocomplete crashes or it takes a long time.  Have you had better experience with any other completion plugins?

Finally, if I add docblock comments to methods, will this plugin parse that information and display it to me?  If I add type hints, I see those in the autocomplete but I do not see any docblock info.

**Comment by complex857** [comment]
> I tried updating the input_patterns to handle 'new':

Hmm, yeah, vim have it's own special flavor of regexp patterns, usually meaning you need a lots more `\`.
The [`\h`](http://vimdoc.sourceforge.net/htmldoc/pattern.html#/\h) means `[A-Za-z_]` so you don't want that after the `new` but a whitespace, and you need to add `\` before the pipes (`|`) and parents and almost everything (unless you are in [veri magic mode](http://vimdoc.sourceforge.net/htmldoc/pattern.html#/\v)... but i digress). 
Try this one (I've added a bunch of keywords next to `new` too):
```
'[^. \t]->\|\h\w*::\|\(new\|use\|extends\|implements\)\s'
```

> On a related note, have you used this plugin on large PHP projects? One of my large projects have a 13 MB tags file and when I try to run omnicomplete sometimes neocomplete crashes or it takes a long time.

I'm afraid never tried on anything that big, running a small search it looks like that most of my tag files are around 1 MB. 
I'm afraid that the fact is that it's just too slow for running it in this "always on" way. Unless completing built-in stuffs, it reads source files, opens buffers, runs multiple search/replace with a bunch of pretty hairy patterns... there is some caching to speed things up, but there's much to be improved upon. Some major reconstructing of the plugin's internals is needed, but I'm in more of a maintenance mode now and frankly, had more fun adding new features than redoing old ones (-:

> Have you had better experience with any other completion plugins?

The only other general php one that I know of is the previously mentioned [phpcomplete-extended](https://github.com/m2mdas/phpcomplete-extended) plugin. That one has a really awesome performance and accuracy, featuring a real php parser/tokenizer instead of a bunch of cluncky regexps like this one do, and uses the same internal data structures for built-in and user stuff. It's a pity that it seems to be orphaned at this moment. I had some plans to do a ctags -> classindex converter, so you could use the plugin on non-composer projects, but only got so far as adding docblock collecting to ctags.

The other somewhat comparable is [wordpress.vim](https://github.com/dsawardekar/wordpress.vim) which just fills the built-in info hashes with wordpress functions and classes so it's pretty fast, but it's wordpress only.

**Comment by complex857** [comment]
I'm going to close this issue, please let me know if you are still having problems.
