### ISSUE TITLE
Multi-line function parameters cause object type lookup failure.

### ISSUE THREAD

**Issue by FlickerBean** [shawncplus/phpcomplete.vim#59]
eg:
```    
    /**
     * __construct
     *
     * @param EloquentApi $api                 Used as an IIP server connector
     * @param OSRecordApiInterface $record_api Connect to OSRecord
     *
     * @return void
     * @access public
     */
    public function __construct(
        EloquentApi $api,
        OSRecordApiInterface $record_api
    ) {
        $api->
    }
```
The above code fails to find the object type of $api due to the regex's only searching on a single line at a time for: 
(pseudo)
```
// object = 'api'
'function\s\+'.function_name_pattern.'\(.\{-}'.object
```
This applies to docblocks aswell, so even if you have the docblock @param and a type-hint in the declaration, it still fails.
We could extend the function to search back until it finds 
```
'function\s\+'.function_name_pattern.'\(' 
```
and then search forward lines again for the @param until we hit a ')' but this feels complex.

I'm wondering if there's any reason you didn't try just searching back from the current line for something like:
```
// object = 'api'
class_name_pattern.'\s\+'.object
```
Do you think this would be too broad a match?

**Comment by FlickerBean** [comment]
Another potential option is to search for the opening of a function without a closing parameter bracket. We can then just loop forward through the lines appending them to our function line until we find a closing brace. eg:
```
if matches 'function.function_regex.'(\s$
    match_line = line
    while !matches '.*).*'
        // Search forwards through the lines and append them to match_line
    endwhile
    // Now match_line contains the whole function declaration on a single line and we can treat it the same as we did before
    ...
endif
```
Excuse the aweful semi-pseudo code.

**Comment by complex857** [comment]
I certainly like your second approach more.
When these parts were written the code were looking trough all the lines above the current so I've tried to be as specific as possible to avoid false positives (comments are still an issue). Now this lookup is limited to the current function block, so maybe loosening up the pattern would not be as scary as before.

**Comment by complex857** [comment]
@FlickerBean: I've pushed a change, so that any `function foo(` like line would be picked up, and from there the code will try to grab the typehints from all the lines joined of the function (all the lines to the place of completion that is).

This sould make multiline function declarations work just fine ([example](https://github.com/shawncplus/phpcomplete.vim/blob/6b1ff0846357f92884f6a1367e4c80ddecf20221/tests/fixtures/GetClassName/typehinted_functions.php#L54-60)).
Also moved the docblock matching inside this condition, so those should be picked up as well for multiline function declarations too ([example](https://github.com/shawncplus/phpcomplete.vim/blob/6b1ff0846357f92884f6a1367e4c80ddecf20221/tests/fixtures/GetClassName/function_docblock.php#L43-55)).

I hope this solves your particular issue.

**Comment by FlickerBean** [comment]
Excellent! I will update and test this out over the next week or so.

Thanks for all of your hard work.
