### ISSUE TITLE
Endless loop in context completion if an anonymous function is present above the current line

### ISSUE THREAD

**Issue by mgalang** [shawncplus/phpcomplete.vim#64]
I noticed that there seems to be an endless loop somewhere when doing context completion with -> or :: if there is an anonymous function above the line where you're writing your code.

Test case below:

    <?php
    
    class Test{
      public function foo(){}
            
      public static function bar(){}
    }
    
    $test = new Test(); 
    
    function(){}
    
    // let's do some code completion here
    $test->
    // vim hangs

I ran vim debugger and this is the output:
    
    calling function phpcomplete#CompletePHP..phpcomplete#GetClassName..phpcomplete#GetDocBlock([],
    
    function phpcomplete#CompletePHP..phpcomplete#GetClassName..phpcomplete#GetDocBlock returning ''
    
    continuing in function phpcomplete#CompletePHP..phpcomplete#GetClassName

**Comment by complex857** [comment]
Thank you very much for the report.
I've pushed two commits that should fix this (almost a brownpaper i must admit). As it turns out, I've forgot about what copies a list and what not in vimscript, please give it a try!

To make the example work as-is the in-file-class-search needed to be fixed too to be less picky about formatting.

**Comment by mgalang** [comment]
That was quick! It works now, thanks! :thumbsup:
