### ISSUE TITLE
Use vim-php/phpctags instead of ctags

### ISSUE THREAD

**Issue by jinleileiking** [shawncplus/phpcomplete.vim#66]
As b4n / ctags is not maintained today, Why not use phpctags ?

**Comment by complex857** [comment]
For the plugin itself it doesn't really matter what's been used to create the `tags` file itself.

I personally haven't been following the life of the phpctags project, did try it a few years back but it seemed to just stop parsing on the first parse error and because of that I couldn't use it as a day-to-day tool, but that was years back. The original ctags has a well maintained fork in [fishman/ctags](https://github.com/fishman/ctags) (b4n is a collaborator in that repo too) and i like the raw speed of it too.

The plugin itself doesn't "use" ctags in a sense that it doesn't attempt to call it directly, what do you mean by "use"?

**Comment by ZzAntares** [comment]
@jinleileiking have you confirmed that phpctags works ok with this plugin?

**Comment by complex857** [comment]
I'm gonna close this now, if you need anything else let me know.
